[2024-11-27T22:32:15.176+0000] {processor.py:186} INFO - Started process (PID=663) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:32:15.177+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:32:15.179+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:32:15.179+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:32:15.208+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:32:15.204+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:32:15.210+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:32:15.227+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.055 seconds
[2024-11-27T22:32:45.294+0000] {processor.py:186} INFO - Started process (PID=727) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:32:45.295+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:32:45.297+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:32:45.297+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:32:45.330+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:32:45.325+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:32:45.332+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:32:45.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.081 seconds
[2024-11-27T22:33:15.603+0000] {processor.py:186} INFO - Started process (PID=791) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:33:15.604+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:33:15.606+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:33:15.606+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:33:15.624+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:33:15.621+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:33:15.626+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:33:15.642+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.042 seconds
[2024-11-27T22:33:45.849+0000] {processor.py:186} INFO - Started process (PID=855) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:33:45.850+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:33:45.852+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:33:45.852+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:33:45.866+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:33:45.864+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:33:45.867+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:33:45.883+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.042 seconds
[2024-11-27T22:34:16.085+0000] {processor.py:186} INFO - Started process (PID=919) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:34:16.085+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:34:16.087+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:34:16.087+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:34:16.104+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:34:16.101+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:34:16.105+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:34:16.131+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.051 seconds
[2024-11-27T22:34:46.288+0000] {processor.py:186} INFO - Started process (PID=983) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:34:46.289+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:34:46.292+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:34:46.291+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:34:46.311+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:34:46.307+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:34:46.313+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:34:46.330+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.047 seconds
[2024-11-27T22:35:16.851+0000] {processor.py:186} INFO - Started process (PID=1047) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:35:16.852+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:35:16.854+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:35:16.854+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:35:16.869+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:35:16.866+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:35:16.870+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:35:16.889+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.043 seconds
[2024-11-27T22:35:47.225+0000] {processor.py:186} INFO - Started process (PID=1111) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:35:47.226+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:35:47.229+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:35:47.229+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:35:47.245+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:35:47.242+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:35:47.246+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:35:47.274+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.053 seconds
[2024-11-27T22:36:17.354+0000] {processor.py:186} INFO - Started process (PID=1175) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:36:17.355+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:36:17.357+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:36:17.357+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:36:17.372+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:36:17.369+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:36:17.373+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:36:17.400+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.050 seconds
[2024-11-27T22:36:47.816+0000] {processor.py:186} INFO - Started process (PID=1239) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:36:47.817+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:36:47.819+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:36:47.819+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:36:47.835+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:36:47.832+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:36:47.837+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:36:47.852+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.040 seconds
[2024-11-27T22:37:35.673+0000] {processor.py:186} INFO - Started process (PID=34) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:37:35.680+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:37:35.688+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:37:35.687+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:37:35.725+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:37:35.717+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:37:35.729+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:37:35.774+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.113 seconds
[2024-11-27T22:38:06.687+0000] {processor.py:186} INFO - Started process (PID=100) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:38:06.688+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:38:06.690+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:38:06.690+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:38:06.733+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:38:06.704+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:38:06.735+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:38:06.759+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.077 seconds
[2024-11-27T22:38:37.758+0000] {processor.py:186} INFO - Started process (PID=165) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:38:37.759+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:38:37.761+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:38:37.761+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:38:37.779+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:38:37.774+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:38:37.780+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:38:37.803+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.049 seconds
[2024-11-27T22:39:08.777+0000] {processor.py:186} INFO - Started process (PID=230) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:39:08.777+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:39:08.780+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:39:08.779+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:39:08.794+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:39:08.791+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:39:08.795+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:39:08.816+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.043 seconds
[2024-11-27T22:39:39.799+0000] {processor.py:186} INFO - Started process (PID=295) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:39:39.799+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:39:39.802+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:39:39.801+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:39:39.819+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:39:39.815+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:39:39.821+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:39:39.843+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.048 seconds
[2024-11-27T22:40:29.120+0000] {processor.py:186} INFO - Started process (PID=34) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:40:29.121+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:40:29.123+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:40:29.123+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:40:29.142+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:40:29.138+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:40:29.144+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:40:29.164+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.048 seconds
[2024-11-27T22:40:59.954+0000] {processor.py:186} INFO - Started process (PID=98) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:40:59.954+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:40:59.956+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:40:59.956+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:40:59.972+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:40:59.969+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:40:59.973+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:40:59.991+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.043 seconds
[2024-11-27T22:41:30.128+0000] {processor.py:186} INFO - Started process (PID=163) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:41:30.129+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:41:30.131+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:41:30.130+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:41:30.148+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:41:30.144+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:41:30.150+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:41:30.169+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.045 seconds
[2024-11-27T22:42:00.451+0000] {processor.py:186} INFO - Started process (PID=228) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:42:00.452+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:42:00.454+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:42:00.454+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:42:00.477+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:42:00.473+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:42:00.479+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:42:00.504+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.058 seconds
[2024-11-27T22:42:51.410+0000] {processor.py:186} INFO - Started process (PID=35) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:42:51.411+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:42:51.414+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:42:51.413+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:42:51.431+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:42:51.426+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:42:51.432+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:42:51.452+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.046 seconds
[2024-11-27T22:43:21.592+0000] {processor.py:186} INFO - Started process (PID=100) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:43:21.592+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:43:21.594+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:43:21.594+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:43:21.611+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:43:21.608+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:43:21.612+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:43:21.630+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.043 seconds
[2024-11-27T22:43:51.960+0000] {processor.py:186} INFO - Started process (PID=165) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:43:51.960+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:43:51.962+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:43:51.962+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:43:51.978+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:43:51.975+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:43:51.980+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:43:51.998+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.043 seconds
[2024-11-27T22:44:22.625+0000] {processor.py:186} INFO - Started process (PID=230) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:44:22.626+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:44:22.628+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:44:22.628+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:44:22.642+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:44:22.640+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:44:22.644+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:44:22.660+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.039 seconds
[2024-11-27T22:44:53.371+0000] {processor.py:186} INFO - Started process (PID=295) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:44:53.371+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:44:53.373+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:44:53.373+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:44:53.389+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:44:53.386+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:44:53.390+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:44:53.407+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.040 seconds
[2024-11-27T22:45:23.707+0000] {processor.py:186} INFO - Started process (PID=360) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:45:23.708+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:45:23.710+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:45:23.710+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:45:23.729+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:45:23.724+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:45:23.730+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:45:23.747+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.044 seconds
[2024-11-27T22:45:53.963+0000] {processor.py:186} INFO - Started process (PID=425) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:45:53.963+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:45:53.965+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:45:53.965+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:45:53.979+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:45:53.976+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:45:53.980+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:45:53.998+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.039 seconds
[2024-11-27T22:46:24.341+0000] {processor.py:186} INFO - Started process (PID=490) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:46:24.342+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:46:24.344+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:46:24.344+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:46:24.360+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:46:24.356+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:46:24.361+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:46:24.381+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.044 seconds
[2024-11-27T22:46:55.000+0000] {processor.py:186} INFO - Started process (PID=555) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:46:55.001+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:46:55.004+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:46:55.003+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:46:55.023+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:46:55.020+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:46:55.025+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:46:55.045+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.050 seconds
[2024-11-27T22:47:25.681+0000] {processor.py:186} INFO - Started process (PID=620) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:47:25.682+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:47:25.684+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:47:25.684+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:47:25.704+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:47:25.699+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:47:25.705+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:47:25.726+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.050 seconds
[2024-11-27T22:47:56.031+0000] {processor.py:186} INFO - Started process (PID=685) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:47:56.034+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:47:56.037+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:47:56.035+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:47:56.062+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:47:56.059+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:47:56.064+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:47:56.085+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.058 seconds
[2024-11-27T22:49:14.399+0000] {processor.py:186} INFO - Started process (PID=34) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:49:14.401+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:49:14.405+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:49:14.404+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:49:14.434+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:49:14.429+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:49:14.436+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:49:14.461+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.068 seconds
[2024-11-27T22:49:45.214+0000] {processor.py:186} INFO - Started process (PID=99) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:49:45.215+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:49:45.216+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:49:45.216+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:49:45.233+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:49:45.230+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:49:45.235+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:49:45.254+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.045 seconds
[2024-11-27T22:50:15.625+0000] {processor.py:186} INFO - Started process (PID=164) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:50:15.625+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:50:15.627+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:50:15.627+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:50:15.643+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:50:15.639+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:50:15.644+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:50:15.661+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.041 seconds
[2024-11-27T22:50:46.464+0000] {processor.py:186} INFO - Started process (PID=229) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:50:46.465+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:50:46.467+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:50:46.466+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:50:46.482+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:50:46.479+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:50:46.484+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:50:46.500+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.041 seconds
[2024-11-27T22:51:17.515+0000] {processor.py:186} INFO - Started process (PID=294) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:51:17.516+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:51:17.518+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:51:17.518+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:51:17.536+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:51:17.532+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:51:17.538+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:51:17.555+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.044 seconds
[2024-11-27T22:51:47.872+0000] {processor.py:186} INFO - Started process (PID=359) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:51:47.874+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:51:47.876+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:51:47.876+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:51:47.895+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:51:47.891+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:51:47.897+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:51:47.916+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.049 seconds
[2024-11-27T22:52:18.377+0000] {processor.py:186} INFO - Started process (PID=425) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:52:18.378+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:52:18.380+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:52:18.380+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:52:18.396+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:52:18.392+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:52:18.397+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:52:18.420+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.047 seconds
[2024-11-27T22:52:48.612+0000] {processor.py:186} INFO - Started process (PID=490) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:52:48.613+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:52:48.615+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:52:48.614+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:52:48.629+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:52:48.625+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:52:48.630+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:52:48.646+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.039 seconds
[2024-11-27T22:53:18.702+0000] {processor.py:186} INFO - Started process (PID=555) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:53:18.703+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:53:18.705+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:53:18.705+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:53:18.721+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:53:18.718+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:53:18.723+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:53:18.743+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.044 seconds
[2024-11-27T22:53:49.130+0000] {processor.py:186} INFO - Started process (PID=620) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:53:49.131+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:53:49.134+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:53:49.134+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:53:49.150+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:53:49.147+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:53:49.151+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:53:49.168+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.043 seconds
[2024-11-27T22:54:19.572+0000] {processor.py:186} INFO - Started process (PID=685) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:54:19.573+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:54:19.576+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:54:19.575+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:54:19.591+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:54:19.588+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:54:19.593+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:54:19.612+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.045 seconds
[2024-11-27T22:54:50.033+0000] {processor.py:186} INFO - Started process (PID=750) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:54:50.034+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:54:50.037+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:54:50.036+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:54:50.066+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:54:50.062+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:54:50.068+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:54:50.088+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.061 seconds
[2024-11-27T22:55:20.496+0000] {processor.py:186} INFO - Started process (PID=815) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:55:20.497+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:55:20.499+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:55:20.499+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:55:20.520+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:55:20.516+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:55:20.522+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:55:20.546+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.054 seconds
[2024-11-27T22:55:50.760+0000] {processor.py:186} INFO - Started process (PID=886) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:55:50.761+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:55:50.764+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:55:50.763+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:55:50.778+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:55:50.775+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:55:50.780+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:55:50.800+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.044 seconds
[2024-11-27T22:56:21.151+0000] {processor.py:186} INFO - Started process (PID=951) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:56:21.152+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:56:21.155+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:56:21.154+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:56:21.170+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:56:21.167+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:56:21.172+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:56:21.188+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.041 seconds
[2024-11-27T22:56:51.529+0000] {processor.py:186} INFO - Started process (PID=1016) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:56:51.530+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:56:51.532+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:56:51.531+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:56:51.548+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:56:51.545+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:56:51.550+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:56:51.575+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.051 seconds
[2024-11-27T22:57:21.792+0000] {processor.py:186} INFO - Started process (PID=1081) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:57:21.794+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:57:21.802+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:57:21.802+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:57:21.888+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:57:21.868+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:57:21.891+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:57:21.935+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.151 seconds
[2024-11-27T22:57:52.677+0000] {processor.py:186} INFO - Started process (PID=1146) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:57:52.678+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:57:52.680+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:57:52.680+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:57:52.696+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:57:52.692+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:57:52.697+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:57:52.715+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.042 seconds
[2024-11-27T22:58:22.964+0000] {processor.py:186} INFO - Started process (PID=1211) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:58:22.965+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:58:22.966+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:58:22.966+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:58:22.984+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:58:22.980+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:58:22.986+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:58:23.004+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.044 seconds
[2024-11-27T22:58:53.082+0000] {processor.py:186} INFO - Started process (PID=1276) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:58:53.083+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:58:53.086+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:58:53.085+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:58:53.101+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:58:53.098+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:58:53.103+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:58:53.119+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.041 seconds
[2024-11-27T22:59:23.303+0000] {processor.py:186} INFO - Started process (PID=1341) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:59:23.304+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:59:23.306+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:59:23.306+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:59:23.323+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:59:23.319+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:59:23.325+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:59:23.342+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.044 seconds
[2024-11-27T22:59:53.689+0000] {processor.py:186} INFO - Started process (PID=1407) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:59:53.690+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T22:59:53.692+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:59:53.692+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:59:53.708+0000] {logging_mixin.py:190} INFO - [2024-11-27T22:59:53.704+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T22:59:53.709+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T22:59:53.727+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.042 seconds
[2024-11-27T23:00:24.237+0000] {processor.py:186} INFO - Started process (PID=1472) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:00:24.238+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:00:24.240+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:00:24.240+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:00:24.259+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:00:24.254+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:00:24.260+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:00:24.281+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.048 seconds
[2024-11-27T23:00:54.359+0000] {processor.py:186} INFO - Started process (PID=1537) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:00:54.359+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:00:54.362+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:00:54.362+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:00:54.380+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:00:54.376+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:00:54.381+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:00:54.400+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.046 seconds
[2024-11-27T23:01:24.733+0000] {processor.py:186} INFO - Started process (PID=1601) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:01:24.734+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:01:24.736+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:01:24.736+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:01:24.749+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:01:24.746+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:01:24.750+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:01:24.769+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.040 seconds
[2024-11-27T23:01:55.200+0000] {processor.py:186} INFO - Started process (PID=1665) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:01:55.200+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:01:55.203+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:01:55.203+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:01:55.218+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:01:55.215+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:01:55.219+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:01:55.235+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.040 seconds
[2024-11-27T23:02:25.356+0000] {processor.py:186} INFO - Started process (PID=1730) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:02:25.357+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:02:25.360+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:02:25.359+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:02:25.379+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:02:25.374+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:02:25.381+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:02:25.400+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.049 seconds
[2024-11-27T23:02:55.745+0000] {processor.py:186} INFO - Started process (PID=1795) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:02:55.746+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:02:55.748+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:02:55.747+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:02:55.763+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:02:55.760+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:02:55.765+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:02:55.783+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.042 seconds
[2024-11-27T23:03:26.112+0000] {processor.py:186} INFO - Started process (PID=1859) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:03:26.113+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:03:26.115+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:03:26.115+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:03:26.153+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:03:26.149+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:03:26.154+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:03:26.173+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.065 seconds
[2024-11-27T23:03:56.568+0000] {processor.py:186} INFO - Started process (PID=1924) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:03:56.569+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:03:56.571+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:03:56.571+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:03:56.588+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:03:56.584+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:03:56.589+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:03:56.609+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.045 seconds
[2024-11-27T23:04:27.097+0000] {processor.py:186} INFO - Started process (PID=1989) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:04:27.098+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:04:27.101+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:04:27.100+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:04:27.120+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:04:27.116+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:04:27.122+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:04:27.141+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.049 seconds
[2024-11-27T23:04:58.063+0000] {processor.py:186} INFO - Started process (PID=2054) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:04:58.064+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:04:58.066+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:04:58.065+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:04:58.081+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:04:58.078+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:04:58.082+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:04:58.101+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.042 seconds
[2024-11-27T23:05:28.475+0000] {processor.py:186} INFO - Started process (PID=2119) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:05:28.476+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:05:28.478+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:05:28.477+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:05:28.498+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:05:28.491+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:05:28.500+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:05:28.519+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.049 seconds
[2024-11-27T23:06:00.885+0000] {processor.py:186} INFO - Started process (PID=2175) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:06:00.886+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:06:00.888+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:06:00.888+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:06:00.907+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:06:00.903+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:06:00.909+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:06:00.930+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.051 seconds
[2024-11-27T23:06:32.065+0000] {processor.py:186} INFO - Started process (PID=2236) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:06:32.066+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:06:32.070+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:06:32.069+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:06:32.113+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:06:32.107+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:06:32.115+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:06:32.138+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.079 seconds
[2024-11-27T23:07:02.263+0000] {processor.py:186} INFO - Started process (PID=2296) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:07:02.264+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:07:02.266+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:07:02.266+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:07:02.280+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:07:02.277+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:07:02.281+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:07:02.298+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.039 seconds
[2024-11-27T23:07:32.939+0000] {processor.py:186} INFO - Started process (PID=2359) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:07:32.940+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:07:32.947+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:07:32.946+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:07:32.964+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:07:32.961+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:07:32.966+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:07:32.985+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.049 seconds
[2024-11-27T23:08:04.002+0000] {processor.py:186} INFO - Started process (PID=2425) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:08:04.003+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:08:04.005+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:08:04.005+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:08:04.019+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:08:04.017+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:08:04.021+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:08:04.038+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.040 seconds
[2024-11-27T23:08:34.122+0000] {processor.py:186} INFO - Started process (PID=2490) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:08:34.122+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:08:34.125+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:08:34.125+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:08:34.140+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:08:34.137+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:08:34.142+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:08:34.159+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.042 seconds
[2024-11-27T23:09:04.446+0000] {processor.py:186} INFO - Started process (PID=2555) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:09:04.447+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:09:04.448+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:09:04.448+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:09:04.463+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:09:04.460+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:09:04.464+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:09:04.479+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.037 seconds
[2024-11-27T23:09:35.133+0000] {processor.py:186} INFO - Started process (PID=2610) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:09:35.134+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:09:35.137+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:09:35.136+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:09:35.153+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:09:35.151+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:09:35.155+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:09:35.175+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.046 seconds
[2024-11-27T23:10:06.145+0000] {processor.py:186} INFO - Started process (PID=2673) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:10:06.146+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:10:06.148+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:10:06.147+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:10:06.162+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:10:06.158+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:10:06.163+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:10:06.180+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.040 seconds
[2024-11-27T23:10:36.259+0000] {processor.py:186} INFO - Started process (PID=2727) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:10:36.260+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:10:36.262+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:10:36.262+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:10:36.279+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:10:36.276+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:10:36.281+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:10:36.299+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.044 seconds
[2024-11-27T23:11:06.795+0000] {processor.py:186} INFO - Started process (PID=2792) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:11:06.796+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:11:06.799+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:11:06.799+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:11:06.818+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:11:06.813+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:11:06.819+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:11:06.840+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.051 seconds
[2024-11-27T23:11:37.380+0000] {processor.py:186} INFO - Started process (PID=2857) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:11:37.381+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:11:37.384+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:11:37.384+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:11:37.409+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:11:37.402+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:11:37.411+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:11:37.433+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.059 seconds
[2024-11-27T23:12:07.655+0000] {processor.py:186} INFO - Started process (PID=2922) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:12:07.656+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:12:07.658+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:12:07.658+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:12:07.674+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:12:07.670+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:12:07.675+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:12:07.692+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.041 seconds
[2024-11-27T23:12:38.305+0000] {processor.py:186} INFO - Started process (PID=2987) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:12:38.306+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:12:38.308+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:12:38.308+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:12:38.326+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:12:38.322+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:12:38.327+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:12:38.346+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.047 seconds
[2024-11-27T23:13:09.184+0000] {processor.py:186} INFO - Started process (PID=3052) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:13:09.185+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:13:09.188+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:13:09.187+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:13:09.214+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:13:09.208+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:13:09.216+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:13:09.252+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.076 seconds
[2024-11-27T23:13:39.650+0000] {processor.py:186} INFO - Started process (PID=3117) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:13:39.653+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:13:39.656+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:13:39.655+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:13:39.722+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:13:39.716+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:13:39.726+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:13:39.805+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.170 seconds
[2024-11-27T23:14:09.903+0000] {processor.py:186} INFO - Started process (PID=3182) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:14:09.907+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:14:09.911+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:14:09.910+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:14:09.934+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:14:09.929+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:14:09.937+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:14:09.963+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.065 seconds
[2024-11-27T23:14:40.009+0000] {processor.py:186} INFO - Started process (PID=3247) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:14:40.010+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:14:40.012+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:14:40.012+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:14:40.030+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:14:40.026+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:14:40.031+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:14:40.063+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.057 seconds
[2024-11-27T23:16:18.414+0000] {processor.py:186} INFO - Started process (PID=33) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:16:18.415+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:16:18.418+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:16:18.418+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:16:18.442+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:16:18.438+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:16:18.444+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:16:18.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.062 seconds
[2024-11-27T23:16:48.855+0000] {processor.py:186} INFO - Started process (PID=99) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:16:48.855+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:16:48.857+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:16:48.857+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:16:48.873+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:16:48.870+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:16:48.874+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:16:48.891+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.040 seconds
[2024-11-27T23:17:19.643+0000] {processor.py:186} INFO - Started process (PID=164) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:17:19.644+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:17:19.646+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:17:19.646+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:17:19.670+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:17:19.665+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:17:19.672+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:17:19.694+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.055 seconds
[2024-11-27T23:17:49.756+0000] {processor.py:186} INFO - Started process (PID=229) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:17:49.757+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:17:49.759+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:17:49.759+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:17:49.775+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:17:49.772+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:17:49.776+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:17:49.793+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.043 seconds
[2024-11-27T23:18:20.043+0000] {processor.py:186} INFO - Started process (PID=294) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:18:20.044+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:18:20.045+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:18:20.045+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:18:20.060+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:18:20.057+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:18:20.061+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:18:20.084+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.046 seconds
[2024-11-27T23:18:25.666+0000] {processor.py:186} INFO - Started process (PID=311) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:18:25.667+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:18:25.669+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:18:25.669+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:18:25.709+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:18:25.705+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:18:25.711+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:18:25.731+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.069 seconds
[2024-11-27T23:18:55.934+0000] {processor.py:186} INFO - Started process (PID=376) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:18:55.935+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:18:55.937+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:18:55.936+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:18:55.953+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:18:55.950+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:18:55.954+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:18:55.980+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.050 seconds
[2024-11-27T23:19:26.376+0000] {processor.py:186} INFO - Started process (PID=442) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:19:26.377+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:19:26.379+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:19:26.379+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:19:26.397+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:19:26.393+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:19:26.398+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:19:26.427+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.056 seconds
[2024-11-27T23:19:56.601+0000] {processor.py:186} INFO - Started process (PID=507) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:19:56.602+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:19:56.604+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:19:56.604+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:19:56.625+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:19:56.621+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:19:56.627+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:19:56.655+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.058 seconds
[2024-11-27T23:20:26.813+0000] {processor.py:186} INFO - Started process (PID=572) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:20:26.814+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:20:26.815+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:20:26.815+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:20:26.831+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:20:26.828+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:20:26.832+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:20:26.856+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.048 seconds
[2024-11-27T23:20:57.244+0000] {processor.py:186} INFO - Started process (PID=637) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:20:57.245+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:20:57.247+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:20:57.246+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:20:57.264+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:20:57.261+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:20:57.265+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:20:57.283+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.044 seconds
[2024-11-27T23:21:27.427+0000] {processor.py:186} INFO - Started process (PID=702) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:21:27.429+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:21:27.430+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:21:27.430+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:21:27.448+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:21:27.444+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:21:27.449+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:21:27.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.043 seconds
[2024-11-27T23:21:57.600+0000] {processor.py:186} INFO - Started process (PID=767) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:21:57.601+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:21:57.602+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:21:57.602+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:21:57.617+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:21:57.615+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:21:57.618+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:21:57.642+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.046 seconds
[2024-11-27T23:22:28.240+0000] {processor.py:186} INFO - Started process (PID=832) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:22:28.241+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:22:28.243+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:22:28.243+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:22:28.262+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:22:28.257+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:22:28.264+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:22:28.280+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.044 seconds
[2024-11-27T23:22:58.529+0000] {processor.py:186} INFO - Started process (PID=897) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:22:58.530+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:22:58.532+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:22:58.532+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:22:58.552+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:22:58.548+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:22:58.553+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:22:58.573+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.048 seconds
[2024-11-27T23:23:29.103+0000] {processor.py:186} INFO - Started process (PID=962) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:23:29.104+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:23:29.105+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:23:29.105+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:23:29.122+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:23:29.119+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:23:29.123+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:23:29.149+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.051 seconds
[2024-11-27T23:23:59.776+0000] {processor.py:186} INFO - Started process (PID=1027) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:23:59.778+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:23:59.780+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:23:59.780+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:23:59.797+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:23:59.794+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:23:59.798+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:23:59.828+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.056 seconds
[2024-11-27T23:24:29.945+0000] {processor.py:186} INFO - Started process (PID=1092) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:24:29.946+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:24:29.948+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:24:29.948+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:24:29.965+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:24:29.961+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:24:29.966+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:24:29.983+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.042 seconds
[2024-11-27T23:25:00.091+0000] {processor.py:186} INFO - Started process (PID=1157) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:25:00.092+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:25:00.094+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:25:00.093+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:25:00.115+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:25:00.111+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:25:00.116+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:25:00.134+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.048 seconds
[2024-11-27T23:25:30.404+0000] {processor.py:186} INFO - Started process (PID=1222) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:25:30.405+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:25:30.407+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:25:30.407+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:25:30.421+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:25:30.419+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:25:30.423+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:25:30.439+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.039 seconds
[2024-11-27T23:26:01.187+0000] {processor.py:186} INFO - Started process (PID=1287) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:26:01.188+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:26:01.190+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:26:01.190+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:26:01.205+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:26:01.202+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:26:01.206+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:26:01.231+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.048 seconds
[2024-11-27T23:26:31.399+0000] {processor.py:186} INFO - Started process (PID=1352) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:26:31.400+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:26:31.403+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:26:31.403+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:26:31.422+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:26:31.418+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:26:31.423+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:26:31.451+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.058 seconds
[2024-11-27T23:27:01.947+0000] {processor.py:186} INFO - Started process (PID=1417) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:27:01.948+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:27:01.950+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:27:01.950+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:27:01.964+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:27:01.962+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:27:01.965+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:27:01.992+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.049 seconds
[2024-11-27T23:27:32.576+0000] {processor.py:186} INFO - Started process (PID=1482) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:27:32.577+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:27:32.579+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:27:32.578+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:27:32.595+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:27:32.592+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:27:32.596+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:27:32.622+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.050 seconds
[2024-11-27T23:28:03.157+0000] {processor.py:186} INFO - Started process (PID=1547) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:28:03.158+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:28:03.161+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:28:03.160+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:28:03.177+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:28:03.174+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:28:03.178+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:28:03.195+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.042 seconds
[2024-11-27T23:28:33.358+0000] {processor.py:186} INFO - Started process (PID=1612) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:28:33.359+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:28:33.361+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:28:33.361+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:28:33.376+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:28:33.373+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:28:33.377+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:28:33.404+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.049 seconds
[2024-11-27T23:29:03.749+0000] {processor.py:186} INFO - Started process (PID=1677) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:29:03.749+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:29:03.751+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:29:03.751+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:29:03.769+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:29:03.766+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:29:03.771+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:29:03.799+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.054 seconds
[2024-11-27T23:29:34.267+0000] {processor.py:186} INFO - Started process (PID=1741) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:29:34.268+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:29:34.270+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:29:34.270+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:29:34.289+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:29:34.285+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:29:34.290+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:29:34.310+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.048 seconds
[2024-11-27T23:30:04.463+0000] {processor.py:186} INFO - Started process (PID=1806) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:30:04.464+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:30:04.465+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:30:04.465+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:30:04.481+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:30:04.477+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:30:04.483+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:30:04.509+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.050 seconds
[2024-11-27T23:30:35.506+0000] {processor.py:186} INFO - Started process (PID=1871) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:30:35.507+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:30:35.509+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:30:35.508+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:30:35.526+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:30:35.522+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:30:35.527+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:30:35.544+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.042 seconds
[2024-11-27T23:31:05.798+0000] {processor.py:186} INFO - Started process (PID=1936) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:31:05.799+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:31:05.801+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:31:05.801+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:31:05.818+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:31:05.815+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:31:05.819+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:31:05.849+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.059 seconds
[2024-11-27T23:31:35.924+0000] {processor.py:186} INFO - Started process (PID=2001) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:31:35.925+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:31:35.927+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:31:35.927+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:31:35.946+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:31:35.943+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:31:35.948+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:31:35.966+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.046 seconds
[2024-11-27T23:32:06.064+0000] {processor.py:186} INFO - Started process (PID=2066) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:32:06.064+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:32:06.067+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:32:06.066+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:32:06.127+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:32:06.124+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:32:06.128+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:32:06.146+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.087 seconds
[2024-11-27T23:32:36.968+0000] {processor.py:186} INFO - Started process (PID=2131) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:32:36.968+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:32:36.970+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:32:36.970+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:32:36.985+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:32:36.982+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:32:36.987+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:32:37.014+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.051 seconds
[2024-11-27T23:33:07.421+0000] {processor.py:186} INFO - Started process (PID=2196) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:33:07.422+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:33:07.424+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:33:07.423+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:33:07.439+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:33:07.435+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:33:07.441+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:33:07.456+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.039 seconds
[2024-11-27T23:33:38.406+0000] {processor.py:186} INFO - Started process (PID=2261) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:33:38.407+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:33:38.409+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:33:38.409+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:33:38.430+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:33:38.427+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:33:38.432+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:33:38.451+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.049 seconds
[2024-11-27T23:34:08.646+0000] {processor.py:186} INFO - Started process (PID=2326) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:34:08.647+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:34:08.648+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:34:08.648+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:34:08.664+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:34:08.661+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:34:08.666+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:34:08.692+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.050 seconds
[2024-11-27T23:34:38.795+0000] {processor.py:186} INFO - Started process (PID=2391) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:34:38.796+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:34:38.798+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:34:38.797+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:34:38.813+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:34:38.811+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:34:38.815+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:34:38.834+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.043 seconds
[2024-11-27T23:35:09.749+0000] {processor.py:186} INFO - Started process (PID=2455) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:35:09.750+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:35:09.752+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:35:09.752+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:35:09.766+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:35:09.763+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:35:09.767+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:35:09.782+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.038 seconds
[2024-11-27T23:35:39.871+0000] {processor.py:186} INFO - Started process (PID=2501) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:35:39.871+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:35:39.873+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:35:39.873+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:35:39.891+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:35:39.888+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:35:39.893+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:35:39.912+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.046 seconds
[2024-11-27T23:36:10.167+0000] {processor.py:186} INFO - Started process (PID=2554) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:36:10.168+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:36:10.171+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:36:10.170+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:36:10.186+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:36:10.183+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:36:10.188+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:36:10.204+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.041 seconds
[2024-11-27T23:36:40.451+0000] {processor.py:186} INFO - Started process (PID=2605) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:36:40.451+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:36:40.454+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:36:40.453+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:36:40.471+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:36:40.468+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:36:40.472+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:36:40.488+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.042 seconds
[2024-11-27T23:37:10.967+0000] {processor.py:186} INFO - Started process (PID=2661) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:37:10.967+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:37:10.970+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:37:10.969+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:37:10.987+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:37:10.983+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:37:10.988+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:37:11.005+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.043 seconds
[2024-11-27T23:37:41.328+0000] {processor.py:186} INFO - Started process (PID=2726) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:37:41.329+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:37:41.331+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:37:41.330+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:37:41.347+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:37:41.343+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:37:41.349+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:37:41.366+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.042 seconds
[2024-11-27T23:38:12.108+0000] {processor.py:186} INFO - Started process (PID=2792) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:38:12.109+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:38:12.111+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:38:12.111+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:38:12.127+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:38:12.124+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:38:12.128+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:38:12.154+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.050 seconds
[2024-11-27T23:38:42.389+0000] {processor.py:186} INFO - Started process (PID=2857) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:38:42.390+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:38:42.391+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:38:42.391+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:38:42.408+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:38:42.404+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:38:42.410+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:38:42.436+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.051 seconds
[2024-11-27T23:39:12.794+0000] {processor.py:186} INFO - Started process (PID=2922) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:39:12.795+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:39:12.797+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:39:12.796+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:39:12.813+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:39:12.810+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:39:12.814+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:39:12.829+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.039 seconds
[2024-11-27T23:39:43.275+0000] {processor.py:186} INFO - Started process (PID=2987) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:39:43.276+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:39:43.278+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:39:43.278+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:39:43.298+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:39:43.294+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:39:43.299+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:39:43.317+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.047 seconds
[2024-11-27T23:40:13.440+0000] {processor.py:186} INFO - Started process (PID=3052) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:40:13.441+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:40:13.444+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:40:13.443+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:40:13.461+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:40:13.457+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:40:13.462+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:40:13.489+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.053 seconds
[2024-11-27T23:40:43.678+0000] {processor.py:186} INFO - Started process (PID=3117) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:40:43.679+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:40:43.681+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:40:43.681+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:40:43.696+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:40:43.693+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:40:43.698+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:40:43.724+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.051 seconds
[2024-11-27T23:41:14.381+0000] {processor.py:186} INFO - Started process (PID=3182) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:41:14.382+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:41:14.385+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:41:14.384+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:41:14.403+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:41:14.399+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:41:14.404+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:41:14.422+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.045 seconds
[2024-11-27T23:41:45.062+0000] {processor.py:186} INFO - Started process (PID=3247) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:41:45.062+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:41:45.065+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:41:45.064+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:41:45.081+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:41:45.077+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:41:45.082+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:41:45.099+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.041 seconds
[2024-11-27T23:42:49.318+0000] {processor.py:186} INFO - Started process (PID=34) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:42:49.319+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:42:49.321+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:42:49.321+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:42:49.344+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:42:49.338+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:42:49.346+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:42:49.372+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.060 seconds
[2024-11-27T23:43:19.762+0000] {processor.py:186} INFO - Started process (PID=100) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:43:19.763+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:43:19.765+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:43:19.765+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:43:19.780+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:43:19.777+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:43:19.782+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:43:19.808+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.050 seconds
[2024-11-27T23:43:50.843+0000] {processor.py:186} INFO - Started process (PID=165) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:43:50.844+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:43:50.846+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:43:50.846+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:43:50.861+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:43:50.857+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:43:50.863+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:43:50.884+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.045 seconds
[2024-11-27T23:44:21.422+0000] {processor.py:186} INFO - Started process (PID=230) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:44:21.423+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:44:21.425+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:44:21.424+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:44:21.441+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:44:21.438+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:44:21.443+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:44:21.464+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.046 seconds
[2024-11-27T23:44:51.768+0000] {processor.py:186} INFO - Started process (PID=295) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:44:51.768+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:44:51.770+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:44:51.770+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:44:51.787+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:44:51.783+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:44:51.788+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:44:51.805+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.042 seconds
[2024-11-27T23:45:21.940+0000] {processor.py:186} INFO - Started process (PID=361) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:45:21.941+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:45:21.943+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:45:21.943+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:45:21.960+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:45:21.957+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:45:21.961+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:45:21.979+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.043 seconds
[2024-11-27T23:45:52.322+0000] {processor.py:186} INFO - Started process (PID=426) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:45:52.323+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:45:52.324+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:45:52.324+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:45:52.339+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:45:52.336+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:45:52.340+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:45:52.358+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.041 seconds
[2024-11-27T23:46:22.797+0000] {processor.py:186} INFO - Started process (PID=491) to work on /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:46:22.797+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_processing_dag.py for tasks to queue
[2024-11-27T23:46:22.799+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:46:22.799+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:46:22.816+0000] {logging_mixin.py:190} INFO - [2024-11-27T23:46:22.812+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_processing_dag.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
[2024-11-27T23:46:22.818+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_processing_dag.py
[2024-11-27T23:46:22.836+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_processing_dag.py took 0.044 seconds
